name: ubuntu-brew-2
on:
  workflow_dispatch:
jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      - run: |
          eval "$(/home/linuxbrew/.linuxbrew/bin/brew shellenv)"
          brew install cyan
      - run: cyan --help
      # - run: ipapatch --help
      - run: dpkg --help
